// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AsikWeb.Models.Entidades
{
    public partial class Alcance
    {
        public int AlcCodigo { get; set; }
        public string AlcNombre { get; set; }
    }
}