// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AsikWeb.Models.Entidades
{
    public partial class Clientes
    {
        public int CliCodigo { get; set; }
        public int CliIdenti { get; set; }
        public int? CliDverif { get; set; }
        public string CliNombre { get; set; }
        public string CliTelefo { get; set; }
        public string CliDirecc { get; set; }
        public int? DepCodigo { get; set; }
        public int? CiuCodigo { get; set; }
    }
}