// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AsikWeb.Models.Entidades
{
    public partial class Estados
    {
        public int EstCodigo { get; set; }
        public string EstNombre { get; set; }
    }
}