// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AsikWeb.Models.Entidades
{
    public partial class Herramientas
    {
        public int HerCodigo { get; set; }
        public string HerNombre { get; set; }
        public string HerNumser { get; set; }
        public string HerMarca { get; set; }
        public string HerObser { get; set; }
    }
}