// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;

namespace AsikWeb.Models.Entidades
{
    public partial class Rol
    {
        public Rol()
        {
            Accesoxrol = new HashSet<Accesoxrol>();
        }

        public int RolCodigo { get; set; }
        public string RolNombre { get; set; }

        public virtual ICollection<Accesoxrol> Accesoxrol { get; set; }
    }
}