// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AsikWeb.Models.Service;
using System;
using System.Collections.Generic;

namespace AsikWeb.Models.Entidades
{
    public partial class TipPago 
    {
        public int TipCodigo { get; set; }
        public string TipNombre { get; set; }
        public int TipEstado { get; set; }
    }
}