// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AsikWeb.Models.Entidades
{
    public partial class Usuarios
    {
        public int UsuCodigo { get; set; }
        public int UsuIdenti { get; set; }
        public string UsuNombre { get; set; }
        public string UsuApelli { get; set; }
        public string UsuContra { get; set; }
        public string UsuEmail { get; set; }
        public int UsuEstad { get; set; }
    }
}